name: Callable workflow

on:
  workflow_call:
    inputs:
      CHECKOUT_ACTION_VERSION:
        type: number
        required: true

jobs:
  checkout:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        checkout-version: [ "${{inputs.CHECKOUT_ACTION_VERSION}}" ]
    steps:
      - uses: actions/checkout@v2