name: Callable workflow

on:
  workflow_call:
    inputs:
      CHECKOUT_ACTION_VERSION:
        type: number
        required: true

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v${{inputs.CHECKOUT_ACTION_VERSION}}
        name: checkout